### ISSUE TITLE
Riddle answers

### ISSUE THREAD

**Issue by prunes-git** [BoobBot/YesDaddy_v2#1]
Consider allowing multiple correct answers

For example there is currently two of the same question with different answers...
    ("What has a neck but no head?", "a bottle"),
    ("What has a neck but has no head?", "a guitar"),

Additionally "a shirt" is another correct answer along with other apparel items, you could even perhaps use regex and just match the specific word "bottle, guitar, shirt, jumper, hoody" etc. that way if they type it with "a" or "an" or just the word they would all be considered correct.

**Comment by IamTails** [comment]
Seems like a great idea, feel free to make a PR

**Comment by devoxin** [comment]
Should be added in 63d79ee
